apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-myweb
  name: gitops-myweb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gitops-myweb
  template:
    metadata:
      labels:
        app: gitops-myweb
    spec:
      containers:
      - image: 192.168.1.10:8443/myweb
        name: myweb